language: csharp
mono: none
dotnet: 2.2.103
script:
 - dotnet restore
 - cd PersistentRetryTemplate
 - dotnet build -f netstandard1.4
 - cd ../PersistentRetryTemplate.Tests
 - dotnet build
 - dotnet test